language: c

compiler:
  - gcc

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq cmake; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq openssl; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && ! $(brew list | grep cmake) ]]; then brew install cmake; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && ! $(brew list | grep openssl) ]]; then brew install openssl; fi
  - export PATH=/usr/local/include:/usr/local/opt/openssl/include/:$PATH
  - mkdir -p build && cd build && cmake ..

after_success:
  - cd test && ./unitest -a 1>/dev/null

script:
  - make

install: true

branches:
  only:
    - master

notifications:
  email: false
  irc:
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"

env:
  - LANG="zh_CN.UTF-8"

os:
  - linux
  - osx

osx_image: xcode61
