language: c

compiler:
  - gcc

before_script:
  - sudo apt-get install -qq cmake
  - mkdir -p build && cd build && cmake ..

after_success:
  - cd test && ./test -a 1>/dev/null

script:
  - make

install: true

branches:
  only:
    - master

notifications:
  email: false
  irc:
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"

env:
  - LANG="zh_CN.UTF-8"

os:
  - linux
  - osx

osx_image: xcode61
